apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: web-app
      tier: frontend
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
    spec:
      containers:
        - name: web-app
          image: $DOCKER_IMAGE
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: '128M'
            requests:
              cpu: 50m
              memory: '64M'
      imagePullSecrets:
        - name: gitlab-registry
