apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app
data:
  REACT_APP_API_URL: '$REACT_APP_API_URL'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: web-app
      tier: frontend
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
    spec:
      containers:
        - name: web-app
          image: $DOCKER_IMAGE
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: '128M'
            requests:
              cpu: 50m
              memory: '64M'
      imagePullSecrets:
        - name: gitlab-registry

---

apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web-app
    tier: frontend

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  annotations:
    ingressClassName: traefik
spec:
  rules:
    - host: $PROJECT_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app
                port:
                  number: 80
