services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: frontend
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: backend
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
