apiVersion: v1
kind: ConfigMap
metadata:
  name: web-api
data:
  PORT: '$PORT'
  MONGODB_STRING: "$MONGODB_STRING"
  JWT_SECRET_KEY: "$JWT_SECRET_KEY"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-api
  name: web-api
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: web-api
      tier: backend
  template:
    metadata:
      labels:
        app: web-api
        tier: backend
    spec:
      containers:
        - name: web-api
          image: $DOCKER_IMAGE
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: '128M'
            requests:
              cpu: 50m
              memory: '64M'
      imagePullSecrets:
        - name: gitlab-registry

---

apiVersion: v1
kind: Service
metadata:
  name: web-api
  labels:
    app: web-api
    tier: frontend
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: web-api
    tier: frontend

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-api
  annotations:
    ingressClassName: traefik
spec:
  rules:
    - host: $PROJECT_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-api
                port:
                  number: 4000
